repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy --strict
        entry: .venv/Scripts/python.exe -m mypy --strict src/
        language: system
        pass_filenames: false
        files: ^src/
